export const FETCH_CURRENT_STOCK_HISTORY = 'fetch_current_stock_history'
export const FETCH_STOCKS = 'stocks_reducer';
export const FETCH_CURRENT_STOCK_UPDATE = 'fetch_current_stock_update';
export const UPDATE_CURRENT_TIME = 'update_current_time'
export const CONNECT_SOCKET = 'connect_socket'
export const ADD_STOCK = 'add_stock'; 
export const REMOVE_STOCK = 'remove_stock'
export const SET_CURRENT_TIME = 'set_current_time'
export const SET_CURRENT_CHART ='set_current_chart'
export const SET_CURRENT_STOCK = 'set_current_stock'
export const FETCH_INITIAL_DATA = 'set_initial_data'
export const UPDATE_STOCK_LIST = 'update_stock_list'
